---
name: refAddonsManager
main: ref\register\addons\Main
version: 1.0.1
api: [ 4.0.0 ]
authors: [ref-team, PresentKim ]
description: Manager of Addons(ResourcePack and BehaviorPack)
mcpe-protocol: [ 471 ]
...
